// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"context"
	"github.com/google/wire"
	"simple_transaction_app/internal/config"
	"simple_transaction_app/internal/db_manager"
)

// Injectors from wire.go:

func GetApp(ctx context.Context) (*App, func(), error) {
	app := &App{}
	return app, func() {
	}, nil
}

// wire.go:

var configSet = wire.NewSet(config.GetConfig, wire.Bind(new(db_manager.IConfig), new(*config.Config)))

var dbSet = wire.NewSet(db_manager.InitPgsqlConnection, wire.Bind(new(db_manager.IDB), new(*db_manager.DB)))

var repositorySet = wire.NewSet()

var servicesSet = wire.NewSet()

var routesSet = wire.NewSet()

type App struct {
}
